services:
  source_sqlserver:
    container_name: source_sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Teste123045@"
      MSSQL_PID: "Developer"
    volumes:
      - source_sqlserver_data:/var/opt/mssql

volumes:
  source_sqlserver_data:
